"""made the queryType, message, email not to be unique

Revision ID: 096a16f90ae2
Revises: 
Create Date: 2025-05-24 11:19:53.668660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096a16f90ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('queryType',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('person_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('person_message_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('person_queryType_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('person_queryType_key'), ['queryType'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('person_message_key'), ['message'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('person_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('queryType',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
